project_id = "loopin-player-2"

[functions.device-pairing]
verify_jwt = false
entrypoint = "./functions/device-pairing/index.ts"

[functions.player-manifest]
verify_jwt = false
entrypoint = "./functions/player-manifest/index.ts"

[functions.player-media]
verify_jwt = false
entrypoint = "./functions/player-media/index.ts"

[functions.player-commands]
verify_jwt = false
entrypoint = "./functions/player-commands/index.ts"
