package com.loopin.player2.core.sync

import com.loopin.player2.core.cache.MediaSource
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import java.io.File

class UpdateInstallationTest {
 private val dir=createTempDir()
 private val bytes="apk".toByteArray()
 private val sha=java.security.MessageDigest.getInstance("SHA-256").digest(bytes).joinToString(""){"%02x".format(it)}
 private val info=PlayerUpdateInfo("11111111-1111-4111-8111-111111111111",15,"v15","https://example.test/update",bytes.size.toLong(),sha,"com.loopin.player2","a".repeat(64),"STABLE")
 private class Store:UpdateInstallAttemptStore{var value:UpdateInstallAttempt?=null;override fun load()=value;override fun save(value:UpdateInstallAttempt){this.value=value};override fun clear(){value=null}}
 private fun manager():PlayerUpdateManager=PlayerUpdateManager(PlayerUpdateSource{PlayerUpdateSourceResult.Available(info)},UpdateMediaSourceFactory{MediaSource{bytes.inputStream()}},object:PlayerInstaller{override fun availability()=InstallerAvailability.UNAVAILABLE;override fun install(apk:File)=InstallationResult.Failed("unused")},ApkSignatureVerifier{_,_->true},dir,installedVersionCode=14).also{assertTrue(it.prepare(info)is ApkPreparationResult.Ready)}
 @Test fun `install requires prepared artifact`(){val s=Store();val empty=PlayerUpdateManager(PlayerUpdateSource{PlayerUpdateSourceResult.Available(info)},UpdateMediaSourceFactory{MediaSource{bytes.inputStream()}},object:PlayerInstaller{override fun availability()=InstallerAvailability.UNAVAILABLE;override fun install(apk:File)=InstallationResult.Failed("unused")},ApkSignatureVerifier{_,_->true},createTempDir(),installedVersionCode=14);val c=UpdateInstallCoordinator(empty,UpdateInstallAuthorizer{InstallAuthorizationResult.Authorized},fakeInstaller(),s,14);assertEquals(UpdateInstallRequestResult.NoPreparedUpdate,c.requestInstall())}
 @Test fun `valid READY is persisted before installer`(){val s=Store();var saw=false;val c=UpdateInstallCoordinator(manager(),UpdateInstallAuthorizer{InstallAuthorizationResult.Authorized},object:PlatformUpdateInstaller{override fun capability()=InstallationCapability.INTERACTIVE_READY;override fun install(apk:File,attempt:UpdateInstallAttempt):PlatformInstallResult{ saw=s.load()?.state==UpdateInstallationState.INSTALL_REQUESTED;return PlatformInstallResult.Requested}},s,14);assertEquals(UpdateInstallRequestResult.Accepted,c.requestInstall());assertTrue(saw);assertEquals(UpdateInstallationState.INSTALLING,s.value?.state)}
 @Test fun `revoked release is not installed`(){var called=false;val c=UpdateInstallCoordinator(manager(),UpdateInstallAuthorizer{InstallAuthorizationResult.Unauthorized},object:PlatformUpdateInstaller{override fun capability()=InstallationCapability.INTERACTIVE_READY;override fun install(apk:File,attempt:UpdateInstallAttempt):PlatformInstallResult{called=true;return PlatformInstallResult.Requested}},Store(),14);assertEquals(UpdateInstallRequestResult.NotAuthorized,c.requestInstall());assertFalse(called)}
 @Test fun `permission required is explicit`(){val s=Store();val c=UpdateInstallCoordinator(manager(),UpdateInstallAuthorizer{InstallAuthorizationResult.Authorized},fakeInstaller(PlatformInstallResult.PermissionRequired),s,14);assertEquals(UpdateInstallRequestResult.PermissionRequired,c.requestInstall());assertEquals(UpdateInstallationState.INSTALL_PERMISSION_REQUIRED,s.value?.state)}
 @Test fun `platform failure keeps retryable artifact and stable code`(){val s=Store();val c=UpdateInstallCoordinator(manager(),UpdateInstallAuthorizer{InstallAuthorizationResult.Authorized},fakeInstaller(PlatformInstallResult.Failed("STORAGE")),s,14);assertEquals(UpdateInstallRequestResult.Failed("STORAGE"),c.requestInstall());assertEquals("STORAGE",s.value?.failureCode)}
 @Test fun `unpaired device is rejected`(){val c=UpdateInstallCoordinator(manager(),UpdateInstallAuthorizer{InstallAuthorizationResult.Authorized},fakeInstaller(),Store(),14,{false});assertEquals(UpdateInstallRequestResult.NotAuthorized,c.requestInstall())}
 @Test fun `startup detects exact target version`(){val s=Store();s.value=attempt();val c=UpdateInstallCoordinator(manager(),UpdateInstallAuthorizer{InstallAuthorizationResult.Authorized},fakeInstaller(),s,15);assertEquals(UpdateInstallationState.POST_UPDATE_VERIFYING,c.verifyAfterStartup(true,true,true)?.state)}
 @Test fun `startup does not invent success on mismatch`(){val s=Store();s.value=attempt();val c=UpdateInstallCoordinator(manager(),UpdateInstallAuthorizer{InstallAuthorizationResult.Authorized},fakeInstaller(),s,14);assertEquals(UpdateInstallationState.INSTALLING,c.verifyAfterStartup(true,true,true)?.state)}
 @Test fun `failed local recovery is explicit`(){val s=Store();s.value=attempt();val c=UpdateInstallCoordinator(manager(),UpdateInstallAuthorizer{InstallAuthorizationResult.Authorized},fakeInstaller(),s,15);assertEquals(UpdateInstallationState.UPDATE_RECOVERY_REQUIRED,c.verifyAfterStartup(false,true,true)?.state)}
 private fun attempt()=UpdateInstallAttempt(info.releaseId,14,15,"v15",sha,1,UpdateInstallationState.INSTALLING)
 private fun fakeInstaller(result:PlatformInstallResult=PlatformInstallResult.Requested)=object:PlatformUpdateInstaller{override fun capability()=InstallationCapability.INTERACTIVE_READY;override fun install(apk:File,attempt:UpdateInstallAttempt)=result}
}
