package com.loopin.player2.core.operations

import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import kotlin.test.*

class RemoteCommandsTest {
    private val health = DeviceHealthSnapshot("internal","582731",1,2,3,4,5,ConnectionStatus.ONLINE,"2.0",PlayerOperationalState.PLAYING,CacheHealth.OK,SyncHealth.OK,6,null,HealthState.HEALTHY)
    private fun command(type:CommandType=CommandType.GET_STATUS,id:String="c1",expires:Long=2_000)=RemoteCommand(id,type,0,expires)
    @Test fun `GET_STATUS returns limited health fields`() { val r=SafeCommandExecutor({health},{"scheduled"},{"reloaded"}).execute(command());assertEquals(CommandCompletionStatus.SUCCEEDED,r.status);assertEquals(setOf("app_version","connection","playback_state","cache_state","sync_state","health_state","free_storage_bytes","last_sync_epoch_ms"),r.result.keys);assertNull(r.result["internal_id"]) }
    @Test fun `SYNC_NOW schedules without waiting`()=assertEquals(mapOf("code" to "scheduled"),SafeCommandExecutor({health},{"scheduled"},{"reloaded"}).execute(command(CommandType.SYNC_NOW)).result)
    @Test fun `SYNC_NOW reports already running`()=assertEquals("already_running",SafeCommandExecutor({health},{"already_running"},{"reloaded"}).execute(command(CommandType.SYNC_NOW)).result["code"])
    @Test fun `RELOAD_PLAYLIST reloads safely`()=assertEquals(mapOf("code" to "reloaded"),SafeCommandExecutor({health},{"scheduled"},{"reloaded"}).execute(command(CommandType.RELOAD_PLAYLIST)).result)
    @Test fun `reload without ACTIVE fails safely`()=assertEquals(CommandCompletionStatus.FAILED,SafeCommandExecutor({health},{"scheduled"},{"no_active_playlist"}).execute(command(CommandType.RELOAD_PLAYLIST)).status)
    @Test fun `future command types remain unsupported`() { for(type in listOf(CommandType.RESTART_PLAYER,CommandType.CLEAR_CACHE,CommandType.CHECK_UPDATE,CommandType.REBOOT_DEVICE,CommandType.CAPTURE_SCREENSHOT,CommandType.UNKNOWN))assertEquals("unsupported",SafeCommandExecutor({health},{"scheduled"},{"reloaded"}).execute(command(type)).result["code"]) }
    @Test fun `request uses bearer and redacts credential`() { val secret="x".repeat(43);val r=DeviceCommandRequest.create("https://example.com",secret);assertEquals("Bearer $secret",r.headers["Authorization"]);assertFalse(r.toString().contains(secret)) }
    @Test fun `unpaired and missing credential do not fetch`() { val t=FakeTransport();assertEquals(CommandDispatchResult.SkippedUnpaired,dispatcher(t,pairing=PairingState.UNPAIRED).dispatch());assertEquals(CommandDispatchResult.SkippedMissingCredential,dispatcher(t,secret=null).dispatch());assertEquals(0,t.fetches) }
    @Test fun `empty 200 is successful`()=assertEquals(CommandDispatchResult.Success(0),dispatcher(FakeTransport()).dispatch())
    @Test fun `batch executes and completes up to five`() { val t=FakeTransport((1..6).map{command(id="c$it")});val r=dispatcher(t).dispatch();assertEquals(CommandDispatchResult.Success(5),r);assertEquals(5,t.completed.size) }
    @Test fun `expired command never invokes executor`() { var calls=0;val t=FakeTransport(listOf(command(expires=99)));dispatcher(t,now=100,executor=CommandExecutor{calls++;CommandOutcome(CommandCompletionStatus.SUCCEEDED,mapOf("code" to "bad"))}).dispatch();assertEquals(0,calls);assertEquals("expired",t.completed.single().second.result["code"]) }
    @Test fun `duplicate command replays stored result without action`() { var calls=0;val store=InMemoryExecutedCommandStore();val t=FakeTransport(listOf(command()));val d=dispatcher(t,store=store,executor=CommandExecutor{calls++;CommandOutcome(CommandCompletionStatus.SUCCEEDED,mapOf("code" to "scheduled"))});d.dispatch();d.dispatch();assertEquals(1,calls);assertEquals(2,t.completed.size) }
    @Test fun `recreated dispatcher preserves replay store`() { var calls=0;val store=InMemoryExecutedCommandStore();dispatcher(FakeTransport(listOf(command())),store=store,executor=CommandExecutor{calls++;CommandOutcome(CommandCompletionStatus.SUCCEEDED,mapOf("code" to "scheduled"))}).dispatch();dispatcher(FakeTransport(listOf(command())),store=store,executor=CommandExecutor{calls++;error("replayed")}).dispatch();assertEquals(1,calls) }
    @Test fun `401 and 5xx remain explicit`() { assertEquals(CommandDispatchResult.Unauthorized,dispatcher(FakeTransport(fetch=CommandFetchResult.Unauthorized)).dispatch());assertEquals(CommandDispatchResult.Failed(true),dispatcher(FakeTransport(fetch=CommandFetchResult.Failed(true))).dispatch()) }
    @Test fun `completion failure is reported and outcome stays persisted`() { val store=InMemoryExecutedCommandStore();val t=FakeTransport(listOf(command()),completion=CommandCompletionResult.Failed(true));assertEquals(CommandDispatchResult.Success(1,1),dispatcher(t,store=store).dispatch());assertNotNull(store.find("c1")) }
    @Test fun `completion unauthorized uses authentication backoff`() { val t=FakeTransport(listOf(command()),completion=CommandCompletionResult.Unauthorized);assertEquals(CommandDispatchResult.Unauthorized,dispatcher(t).dispatch()) }
    @Test fun `concurrent command fetch is rejected`() { val entered=CountDownLatch(1);val release=CountDownLatch(1);val transport=object:DeviceCommandTransport{override fun fetch(request:DeviceCommandRequest):CommandFetchResult{entered.countDown();release.await(2,TimeUnit.SECONDS);return CommandFetchResult.Success(emptyList())};override fun complete(request:DeviceCommandRequest,commandId:String,outcome:CommandOutcome)=CommandCompletionResult.Success};val d=dispatcher(transport);val first=Thread{d.dispatch()}.apply{start()};assertTrue(entered.await(1,TimeUnit.SECONDS));assertEquals(CommandDispatchResult.AlreadyRunning,d.dispatch());release.countDown();first.join() }
    @Test fun `bounded store evicts oldest IDs`() { val s=InMemoryExecutedCommandStore(2);val o=CommandOutcome(CommandCompletionStatus.SUCCEEDED,mapOf("code" to "ok"));s.remember("1",o);s.remember("2",o);s.remember("3",o);assertNull(s.find("1"));assertNotNull(s.find("3")) }
    @Test fun `backoff is bounded and success resets normal interval`() { val p=CommandBackoffPolicy();assertEquals(60_000,p.delayAfter(CommandDispatchResult.Failed(true),1));assertEquals(300_000,p.delayAfter(CommandDispatchResult.Failed(true),2));assertEquals(900_000,p.delayAfter(CommandDispatchResult.Failed(true),3));assertEquals(1_800_000,p.delayAfter(CommandDispatchResult.Failed(true),9));assertEquals(3_600_000,p.delayAfter(CommandDispatchResult.Unauthorized,1));assertEquals(60_000,p.delayAfter(CommandDispatchResult.Success(0),0)) }
    private fun dispatcher(t:DeviceCommandTransport,pairing:PairingState=PairingState.PAIRED,secret:String?="s".repeat(43),now:Long=1_000,store:ExecutedCommandStore=InMemoryExecutedCommandStore(),executor:CommandExecutor=SafeCommandExecutor({health},{"scheduled"},{"reloaded"}))=DeviceCommandDispatcher("https://example.com",{pairing},{secret},t,executor,store,{now})
    private class FakeTransport(commands:List<RemoteCommand> = emptyList(),val completion:CommandCompletionResult=CommandCompletionResult.Success,fetch:CommandFetchResult?=null):DeviceCommandTransport{private val response=fetch?:CommandFetchResult.Success(commands);var fetches=0;val completed=mutableListOf<Pair<String,CommandOutcome>>();override fun fetch(request:DeviceCommandRequest):CommandFetchResult{fetches++;return response};override fun complete(request:DeviceCommandRequest,commandId:String,outcome:CommandOutcome):CommandCompletionResult{completed+=commandId to outcome;return completion}}
}
