package com.loopin.player2.core.sync
import com.loopin.player2.core.cache.*
import java.util.concurrent.CopyOnWriteArrayList
import java.util.concurrent.atomic.AtomicBoolean
import java.security.MessageDigest
enum class SyncState{IDLE,CHECKING,UP_TO_DATE,NO_ASSIGNMENT,AUTHENTICATION_FAILED,UPDATE_AVAILABLE,PREPARING,DOWNLOADING,VALIDATING,COMMITTING,SUCCESS,FAILED,OFFLINE}
data class SyncSnapshot(val state:SyncState=SyncState.IDLE,val localVersion:Long?=null,val remoteVersion:Long?=null,val detail:String?=null)
enum class SyncEvent{SYNC_STARTED,SYNC_CHECKED,SYNC_UP_TO_DATE,SYNC_NO_ASSIGNMENT,SYNC_AUTH_FAILED,SYNC_UPDATE_AVAILABLE,SYNC_DOWNLOAD_STARTED,SYNC_DOWNLOAD_COMPLETED,SYNC_VALIDATION_FAILED,SYNC_COMMIT_STARTED,SYNC_COMMIT_SUCCESS,SYNC_FAILED,SYNC_OFFLINE}
fun interface SyncEventSink{fun record(event:SyncEvent,detail:String?)}
sealed interface SyncResult{data class Success(val version:Long):SyncResult;data class UpToDate(val version:Long?):SyncResult;data object NoAssignment:SyncResult;data object AuthenticationFailed:SyncResult;data class Failed(val reason:String,val retryable:Boolean):SyncResult;data class Offline(val reason:String):SyncResult;data object AlreadyRunning:SyncResult}
class SyncManager(private val remoteManifestSource:RemoteManifestSource,private val localManifestSource:LocalManifestSource,private val mediaSourceFactory:RemoteMediaSourceFactory,private val store:TransactionalPlaylistStore,private val events:SyncEventSink=SyncEventSink{_,_->},private val onCommitted:()->Unit={} ){
 private val running=AtomicBoolean();private val listeners=CopyOnWriteArrayList<(SyncSnapshot)->Unit>();@Volatile var snapshot=SyncSnapshot();private set
 fun syncOnce():SyncResult{if(!running.compareAndSet(false,true))return SyncResult.AlreadyRunning;return try{val active=localManifestSource.active();publish(SyncSnapshot(SyncState.CHECKING,active?.playlistVersion));emit(SyncEvent.SYNC_STARTED,null);when(val r=remoteManifestSource.fetch(active)){RemoteManifestResult.Unchanged->up(active?.playlistVersion);RemoteManifestResult.NoAssignment->{publish(snapshot.copy(state=SyncState.NO_ASSIGNMENT));emit(SyncEvent.SYNC_NO_ASSIGNMENT,null);SyncResult.NoAssignment};RemoteManifestResult.AuthenticationFailed->{publish(snapshot.copy(state=SyncState.AUTHENTICATION_FAILED));emit(SyncEvent.SYNC_AUTH_FAILED,null);SyncResult.AuthenticationFailed};is RemoteManifestResult.Offline->{publish(snapshot.copy(state=SyncState.OFFLINE,detail=r.reason));emit(SyncEvent.SYNC_OFFLINE,r.reason);SyncResult.Offline(r.reason)};is RemoteManifestResult.Failed->fail(r.reason,r.retryable);is RemoteManifestResult.Available->sync(r,active)}}finally{running.set(false)}}
 fun subscribe(l:(SyncSnapshot)->Unit):AutoCloseable{listeners+=l;l(snapshot);return AutoCloseable{listeners-=l}}
 private fun sync(r:RemoteManifestResult.Available,active:PublishedVersionRef?):SyncResult{val m=r.manifest;emit(SyncEvent.SYNC_CHECKED,"remote=${m.playlistId}:${m.playlistVersion}");val canonical=MessageDigest.getInstance("SHA-256").digest(VersionedManifestCodec.encode(m).toByteArray()).joinToString(""){"%02x".format(it)};if(active?.manifestSha256==r.manifestSha256||active?.versionRef==canonical)return up(active.playlistVersion);publish(SyncSnapshot(SyncState.UPDATE_AVAILABLE,active?.playlistVersion,m.playlistVersion));emit(SyncEvent.SYNC_UPDATE_AVAILABLE,null);publish(snapshot.copy(state=SyncState.DOWNLOADING));emit(SyncEvent.SYNC_DOWNLOAD_STARTED,"items=${m.items.size}");val p=store.prepare(m,mediaSourceFactory::sourceFor);if(p !is PreparationResult.Ready)return fail((p as PreparationResult.Rejected).reason,true);emit(SyncEvent.SYNC_DOWNLOAD_COMPLETED,"created=${p.createdObjects}");publish(snapshot.copy(state=SyncState.COMMITTING));return when(val c=store.commit(p.versionRef)){is PublicationResult.Committed->{publish(SyncSnapshot(SyncState.SUCCESS,c.activeVersion,m.playlistVersion));emit(SyncEvent.SYNC_COMMIT_SUCCESS,"active=${c.activeVersion}");onCommitted();SyncResult.Success(c.activeVersion)};is PublicationResult.Rejected->fail(c.reason,true)}}
 private fun up(v:Long?):SyncResult{publish(SyncSnapshot(SyncState.UP_TO_DATE,v,v));emit(SyncEvent.SYNC_UP_TO_DATE,null);return SyncResult.UpToDate(v)}
 private fun fail(s:String,r:Boolean):SyncResult{publish(snapshot.copy(state=SyncState.FAILED,detail=s));emit(SyncEvent.SYNC_FAILED,s);return SyncResult.Failed(s,r)}
 private fun publish(v:SyncSnapshot){snapshot=v;listeners.forEach{it(v)}};private fun emit(e:SyncEvent,d:String?)=runCatching{events.record(e,d)}
}
data class SyncRetryPolicy(val regularIntervalMs:Long=300000,val authDelayMs:Long=3600000){fun delayAfterFailure(n:Int)=when(n){1->60000L;2->300000L;3->900000L;else->1800000L}}
